# Currículo A1–A2 de Aula Francés (24 unidades).
# Módulo PURO (sin dependencias de la app) para poder importarlo también
# desde el script de generación de audio en el host.
import hashlib


def audio_slug(fr: str) -> str:
    """URL/fichero de audio determinista para una palabra francesa."""
    return hashlib.md5(fr.encode("utf-8")).hexdigest()[:12]


# type: video | ejercicio | pdf   ·   vocab: [(fr, es), ...]
CURRICULUM = [
    # ---------------- A1 ----------------
    {"level": "A1", "title": "Les salutations", "type": "video", "meta": "Vídeo · TV5Monde A1",
     "vocab": [("bonjour", "hola"), ("bonsoir", "buenas noches"), ("salut", "hola/adiós (informal)"),
               ("au revoir", "adiós"), ("merci", "gracias"), ("s'il vous plaît", "por favor"),
               ("oui", "sí"), ("non", "no"), ("pardon", "perdón"), ("à bientôt", "hasta pronto")]},
    {"level": "A1", "title": "Se présenter", "type": "ejercicio", "meta": "Ejercicio · Le Point du FLE",
     "vocab": [("je m'appelle", "me llamo"), ("comment tu t'appelles ?", "¿cómo te llamas?"),
               ("enchanté", "encantado"), ("j'habite à", "vivo en"), ("je suis", "soy/estoy"),
               ("tu es", "eres/estás"), ("et toi ?", "¿y tú?"), ("j'ai vingt ans", "tengo veinte años")]},
    {"level": "A1", "title": "Les nombres 0–20", "type": "ejercicio", "meta": "Ejercicio · 10 preguntas",
     "vocab": [("un", "uno"), ("deux", "dos"), ("trois", "tres"), ("quatre", "cuatro"),
               ("cinq", "cinco"), ("six", "seis"), ("sept", "siete"), ("huit", "ocho"),
               ("neuf", "nueve"), ("dix", "diez")]},
    {"level": "A1", "title": "La famille", "type": "video", "meta": "Vídeo · 9 min",
     "vocab": [("le père", "el padre"), ("la mère", "la madre"), ("le frère", "el hermano"),
               ("la sœur", "la hermana"), ("les parents", "los padres"), ("le fils", "el hijo"),
               ("la fille", "la hija"), ("la famille", "la familia")]},
    {"level": "A1", "title": "Nationalités et pays", "type": "pdf", "meta": "PDF · 4 págs",
     "vocab": [("la France", "Francia"), ("l'Espagne", "España"), ("français", "francés"),
               ("espagnol", "español"), ("anglais", "inglés"), ("un pays", "un país"),
               ("une ville", "una ciudad"), ("la langue", "el idioma")]},
    {"level": "A1", "title": "Le présent (être, avoir, -er)", "type": "video", "meta": "Vídeo · 12 min",
     "vocab": [("je suis", "soy/estoy"), ("tu es", "eres/estás"), ("il est", "él es/está"),
               ("j'ai", "tengo"), ("tu as", "tienes"), ("parler", "hablar"),
               ("aimer", "gustar/amar"), ("habiter", "vivir")]},
    {"level": "A1", "title": "Les articles (le, la, un, une)", "type": "ejercicio", "meta": "Ejercicio · 12 preguntas",
     "vocab": [("le", "el"), ("la", "la"), ("les", "los/las"), ("un", "un"),
               ("une", "una"), ("des", "unos/unas"), ("l'ami", "el amigo"), ("l'école", "la escuela")]},
    {"level": "A1", "title": "Décrire (couleurs, adjectifs)", "type": "video", "meta": "Vídeo · 8 min",
     "vocab": [("rouge", "rojo"), ("bleu", "azul"), ("vert", "verde"), ("jaune", "amarillo"),
               ("grand", "grande"), ("petit", "pequeño"), ("content", "contento"), ("beau", "guapo/bonito")]},
    {"level": "A1", "title": "L'heure et les jours", "type": "ejercicio", "meta": "Ejercicio · Bonjour de France",
     "vocab": [("quelle heure est-il ?", "¿qué hora es?"), ("il est midi", "es mediodía"),
               ("il est une heure", "es la una"), ("lundi", "lunes"), ("mardi", "martes"),
               ("mercredi", "miércoles"), ("jeudi", "jueves"), ("vendredi", "viernes"),
               ("le week-end", "el fin de semana"), ("aujourd'hui", "hoy")]},
    {"level": "A1", "title": "Au café (la nourriture)", "type": "video", "meta": "Vídeo · TV5Monde A1",
     "vocab": [("un café", "un café"), ("un thé", "un té"), ("une eau", "un agua"),
               ("un croissant", "un cruasán"), ("un sandwich", "un sándwich"), ("l'addition", "la cuenta"),
               ("je voudrais", "quisiera"), ("manger", "comer"), ("boire", "beber"), ("délicieux", "delicioso")]},
    {"level": "A1", "title": "La ville et les directions", "type": "pdf", "meta": "PDF · 5 págs",
     "vocab": [("la rue", "la calle"), ("à gauche", "a la izquierda"), ("à droite", "a la derecha"),
               ("tout droit", "todo recto"), ("la gare", "la estación"), ("le musée", "el museo"),
               ("où est… ?", "¿dónde está…?"), ("près de", "cerca de"), ("loin de", "lejos de"),
               ("le plan", "el plano")]},
    {"level": "A1", "title": "Les loisirs de base", "type": "ejercicio", "meta": "Ejercicio · LearningApps",
     "vocab": [("le sport", "el deporte"), ("la musique", "la música"), ("le cinéma", "el cine"),
               ("lire", "leer"), ("danser", "bailar"), ("voyager", "viajar"), ("jouer", "jugar"),
               ("j'aime", "me gusta"), ("je n'aime pas", "no me gusta"), ("le temps libre", "el tiempo libre")]},
    # ---------------- A2 ----------------
    {"level": "A2", "title": "Le passé composé", "type": "video", "meta": "Vídeo · 14 min",
     "vocab": [("hier", "ayer"), ("j'ai mangé", "comí/he comido"), ("j'ai fait", "hice/he hecho"),
               ("je suis allé", "fui/he ido"), ("j'ai vu", "vi/he visto"), ("le participe passé", "el participio"),
               ("déjà", "ya"), ("ne… pas encore", "todavía no"), ("la semaine dernière", "la semana pasada"),
               ("finir", "terminar")]},
    {"level": "A2", "title": "L'imparfait", "type": "video", "meta": "Vídeo · 11 min",
     "vocab": [("quand j'étais petit", "cuando era pequeño"), ("il faisait beau", "hacía buen tiempo"),
               ("avant", "antes"), ("souvent", "a menudo"), ("il y avait", "había"), ("je jouais", "jugaba"),
               ("nous habitions", "vivíamos"), ("d'habitude", "normalmente"), ("chaque jour", "cada día"),
               ("autrefois", "antiguamente")]},
    {"level": "A2", "title": "Le futur proche", "type": "ejercicio", "meta": "Ejercicio · 12 preguntas",
     "vocab": [("je vais partir", "voy a salir"), ("aller + infinitif", "ir a + infinitivo"),
               ("demain", "mañana"), ("bientôt", "pronto"), ("ce soir", "esta noche"),
               ("la semaine prochaine", "la semana que viene"), ("je vais faire", "voy a hacer"),
               ("nous allons voir", "vamos a ver"), ("plus tard", "más tarde"), ("tout à l'heure", "dentro de un rato")]},
    {"level": "A2", "title": "La routine (verbes pronominaux)", "type": "video", "meta": "Vídeo · RFI Français facile",
     "vocab": [("se lever", "levantarse"), ("se laver", "lavarse"), ("s'habiller", "vestirse"),
               ("se coucher", "acostarse"), ("se réveiller", "despertarse"), ("le matin", "por la mañana"),
               ("le soir", "por la noche"), ("d'abord", "primero"), ("ensuite", "después"), ("se dépêcher", "darse prisa")]},
    {"level": "A2", "title": "Le corps et la santé", "type": "ejercicio", "meta": "Ejercicio · Liveworksheet",
     "vocab": [("la tête", "la cabeza"), ("le bras", "el brazo"), ("la jambe", "la pierna"),
               ("le ventre", "la barriga"), ("j'ai mal", "me duele"), ("être malade", "estar enfermo"),
               ("le médecin", "el médico"), ("la pharmacie", "la farmacia"), ("un médicament", "un medicamento"),
               ("se sentir bien", "sentirse bien")]},
    {"level": "A2", "title": "Les courses (quantités, partitifs)", "type": "video", "meta": "Vídeo · 10 min",
     "vocab": [("du pain", "pan"), ("de l'eau", "agua"), ("de la viande", "carne"),
               ("un kilo de", "un kilo de"), ("une bouteille de", "una botella de"), ("beaucoup de", "mucho"),
               ("un peu de", "un poco de"), ("le marché", "el mercado"), ("combien ça coûte ?", "¿cuánto cuesta?"),
               ("cher", "caro")]},
    {"level": "A2", "title": "Les vêtements", "type": "pdf", "meta": "PDF · 4 págs",
     "vocab": [("un pantalon", "un pantalón"), ("une chemise", "una camisa"), ("une robe", "un vestido"),
               ("des chaussures", "unos zapatos"), ("un manteau", "un abrigo"), ("porter", "llevar puesto"),
               ("essayer", "probarse"), ("la taille", "la talla"), ("la couleur", "el color"), ("à la mode", "de moda")]},
    {"level": "A2", "title": "Les comparatifs", "type": "ejercicio", "meta": "Ejercicio · Le Point du FLE",
     "vocab": [("plus… que", "más… que"), ("moins… que", "menos… que"), ("aussi… que", "tan… como"),
               ("meilleur", "mejor (adj.)"), ("mieux", "mejor (adv.)"), ("pire", "peor"),
               ("le plus", "el más"), ("le moins", "el menos"), ("comme", "como"), ("autant que", "tanto como")]},
    {"level": "A2", "title": "Le logement", "type": "video", "meta": "Vídeo · 12 min",
     "vocab": [("un appartement", "un piso"), ("une maison", "una casa"), ("la cuisine", "la cocina"),
               ("la chambre", "la habitación"), ("la salle de bains", "el baño"), ("le salon", "el salón"),
               ("louer", "alquilar"), ("le loyer", "el alquiler"), ("meublé", "amueblado"), ("un voisin", "un vecino")]},
    {"level": "A2", "title": "Les projets et le futur", "type": "ejercicio", "meta": "Ejercicio · 10 preguntas",
     "vocab": [("je ferai", "haré"), ("j'irai", "iré"), ("l'année prochaine", "el año que viene"),
               ("un projet", "un proyecto"), ("espérer", "esperar"), ("avoir l'intention de", "tener la intención de"),
               ("réussir", "conseguir/aprobar"), ("un rêve", "un sueño"), ("peut-être", "quizás"),
               ("changer de travail", "cambiar de trabajo")]},
    {"level": "A2", "title": "Raconter une anecdote", "type": "video", "meta": "Vídeo · TV5Monde A2",
     "vocab": [("un jour", "un día"), ("tout à coup", "de repente"), ("alors", "entonces"),
               ("enfin", "por fin"), ("c'était drôle", "fue gracioso"), ("il m'est arrivé", "me pasó"),
               ("puis", "luego"), ("finalement", "al final"), ("incroyable", "increíble"), ("raconter", "contar")]},
    {"level": "A2", "title": "Préparation DELF A2", "type": "pdf", "meta": "PDF · simulacro oficial",
     "vocab": [("la compréhension orale", "comprensión oral"), ("la production écrite", "expresión escrita"),
               ("une consigne", "una instrucción"), ("répondre", "responder"), ("décrire", "describir"),
               ("exprimer une opinion", "expresar una opinión"), ("un examen", "un examen"), ("la note", "la nota"),
               ("réussir l'examen", "aprobar el examen"), ("s'entraîner", "practicar")]},
]
