# Currículo A1–A2 de Aula Francés (24 unidades).
# Módulo PURO (sin dependencias de la app) para poder importarlo también
# desde el script de generación de audio en el host.
import hashlib


def audio_slug(fr: str) -> str:
    """URL/fichero de audio determinista para una palabra francesa."""
    return hashlib.md5(fr.encode("utf-8")).hexdigest()[:12]


# type: video | ejercicio | pdf   ·   vocab: [(fr, es), ...]
CURRICULUM = [
    # ---------------- A1 ----------------
    {"level": "A1", "title": "Les salutations", "type": "video", "meta": "Vídeo · TV5Monde A1",
     "vocab": [("bonjour", "hola / buenos días"), ("bonsoir", "buenas noches"), ("salut", "hola/adiós (informal)"),
               ("au revoir", "adiós"), ("merci", "gracias"), ("s'il vous plaît", "por favor"),
               ("oui", "sí"), ("non", "no"), ("pardon", "perdón"), ("à bientôt", "hasta pronto"),
               ("à demain", "hasta mañana"), ("comment allez-vous ?", "¿cómo está usted?"),
               ("ça va ?", "¿qué tal?"), ("ça va bien", "estoy bien"), ("de rien", "de nada")]},
    {"level": "A1", "title": "Se présenter", "type": "ejercicio", "meta": "Ejercicio · Le Point du FLE",
     "vocab": [("je m'appelle", "me llamo"), ("comment tu t'appelles ?", "¿cómo te llamas?"),
               ("enchanté", "encantado"), ("j'habite à", "vivo en"), ("je suis", "soy/estoy"),
               ("tu es", "eres/estás"), ("et toi ?", "¿y tú?"), ("j'ai vingt ans", "tengo veinte años"),
               ("quel âge as-tu ?", "¿cuántos años tienes?"), ("je viens de", "vengo de"),
               ("je parle français", "hablo francés"), ("mon nom est", "mi nombre es"),
               ("ravi de te rencontrer", "encantado de conocerte"), ("moi aussi", "yo también")]},
    {"level": "A1", "title": "Les nombres 0–20", "type": "ejercicio", "meta": "Ejercicio · 10 preguntas",
     "vocab": [("zéro", "cero"), ("un", "uno"), ("deux", "dos"), ("trois", "tres"), ("quatre", "cuatro"),
               ("cinq", "cinco"), ("six", "seis"), ("sept", "siete"), ("huit", "ocho"), ("neuf", "nueve"),
               ("dix", "diez"), ("onze", "once"), ("douze", "doce"), ("treize", "trece"), ("quatorze", "catorce"),
               ("quinze", "quince"), ("seize", "dieciséis"), ("dix-sept", "diecisiete"),
               ("dix-huit", "dieciocho"), ("dix-neuf", "diecinueve"), ("vingt", "veinte")]},
    {"level": "A1", "title": "La famille", "type": "video", "meta": "Vídeo · 9 min",
     "vocab": [("le père", "el padre"), ("la mère", "la madre"), ("le frère", "el hermano"),
               ("la sœur", "la hermana"), ("les parents", "los padres"), ("le fils", "el hijo"),
               ("la fille", "la hija"), ("la famille", "la familia"), ("le grand-père", "el abuelo"),
               ("la grand-mère", "la abuela"), ("l'oncle", "el tío"), ("la tante", "la tía"),
               ("le cousin", "el primo"), ("le mari", "el marido"), ("la femme", "la mujer/esposa"),
               ("l'enfant", "el niño/a")]},
    {"level": "A1", "title": "Nationalités et pays", "type": "pdf", "meta": "PDF · 4 págs",
     "vocab": [("la France", "Francia"), ("l'Espagne", "España"), ("français", "francés"),
               ("espagnol", "español"), ("anglais", "inglés"), ("un pays", "un país"),
               ("une ville", "una ciudad"), ("la langue", "el idioma"), ("italien", "italiano"),
               ("allemand", "alemán"), ("le Portugal", "Portugal"), ("les États-Unis", "Estados Unidos"),
               ("d'où viens-tu ?", "¿de dónde eres?"), ("étranger", "extranjero")]},
    {"level": "A1", "title": "Le présent (être, avoir, -er)", "type": "video", "meta": "Vídeo · 12 min",
     "vocab": [("je suis", "soy/estoy"), ("tu es", "eres/estás"), ("il est", "él es/está"),
               ("nous sommes", "somos"), ("vous êtes", "sois / es (usted)"), ("ils sont", "son"),
               ("j'ai", "tengo"), ("tu as", "tienes"), ("nous avons", "tenemos"), ("ils ont", "tienen"),
               ("parler", "hablar"), ("aimer", "gustar/amar"), ("habiter", "vivir"),
               ("travailler", "trabajar"), ("regarder", "mirar")]},
    {"level": "A1", "title": "Les articles (le, la, un, une)", "type": "ejercicio", "meta": "Ejercicio · 12 preguntas",
     "vocab": [("le", "el"), ("la", "la"), ("les", "los/las"), ("un", "un"), ("une", "una"),
               ("des", "unos/unas"), ("l'ami", "el amigo"), ("l'école", "la escuela"),
               ("du", "del / algo de"), ("de la", "de la"), ("au", "al"), ("à la", "a la"),
               ("ce", "este"), ("cette", "esta"), ("mon", "mi")]},
    {"level": "A1", "title": "Décrire (couleurs, adjectifs)", "type": "video", "meta": "Vídeo · 8 min",
     "vocab": [("rouge", "rojo"), ("bleu", "azul"), ("vert", "verde"), ("jaune", "amarillo"),
               ("noir", "negro"), ("blanc", "blanco"), ("orange", "naranja"), ("gris", "gris"),
               ("grand", "grande"), ("petit", "pequeño"), ("content", "contento"), ("beau", "guapo/bonito"),
               ("jeune", "joven"), ("gentil", "amable"), ("nouveau", "nuevo")]},
    {"level": "A1", "title": "L'heure et les jours", "type": "ejercicio", "meta": "Ejercicio · Bonjour de France",
     "vocab": [("quelle heure est-il ?", "¿qué hora es?"), ("il est midi", "es mediodía"),
               ("il est une heure", "es la una"), ("il est trois heures", "son las tres"),
               ("et demie", "y media"), ("et quart", "y cuarto"), ("moins le quart", "menos cuarto"),
               ("lundi", "lunes"), ("mardi", "martes"), ("mercredi", "miércoles"), ("jeudi", "jueves"),
               ("vendredi", "viernes"), ("samedi", "sábado"), ("dimanche", "domingo"),
               ("le week-end", "el fin de semana"), ("aujourd'hui", "hoy")]},
    {"level": "A1", "title": "Au café (la nourriture)", "type": "video", "meta": "Vídeo · TV5Monde A1",
     "vocab": [("un café", "un café"), ("un thé", "un té"), ("une eau", "un agua"),
               ("un jus d'orange", "un zumo de naranja"), ("une bière", "una cerveza"),
               ("un croissant", "un cruasán"), ("un sandwich", "un sándwich"), ("l'addition", "la cuenta"),
               ("je voudrais", "quisiera"), ("manger", "comer"), ("boire", "beber"),
               ("le plat", "el plato"), ("le dessert", "el postre"), ("délicieux", "delicioso"),
               ("avoir faim", "tener hambre")]},
    {"level": "A1", "title": "La ville et les directions", "type": "pdf", "meta": "PDF · 5 págs",
     "vocab": [("la rue", "la calle"), ("à gauche", "a la izquierda"), ("à droite", "a la derecha"),
               ("tout droit", "todo recto"), ("la gare", "la estación"), ("le musée", "el museo"),
               ("la place", "la plaza"), ("le pont", "el puente"), ("la banque", "el banco"),
               ("où est… ?", "¿dónde está…?"), ("près de", "cerca de"), ("loin de", "lejos de"),
               ("continuez", "continúe"), ("tournez", "gire"), ("le plan", "el plano")]},
    {"level": "A1", "title": "Les loisirs de base", "type": "ejercicio", "meta": "Ejercicio · LearningApps",
     "vocab": [("le sport", "el deporte"), ("la musique", "la música"), ("le cinéma", "el cine"),
               ("lire", "leer"), ("danser", "bailar"), ("voyager", "viajar"), ("jouer", "jugar"),
               ("chanter", "cantar"), ("se promener", "pasear"), ("faire du sport", "hacer deporte"),
               ("la télévision", "la televisión"), ("j'aime", "me gusta"), ("je n'aime pas", "no me gusta"),
               ("le temps libre", "el tiempo libre")]},
    # ---------------- A2 ----------------
    {"level": "A2", "title": "Le passé composé", "type": "video", "meta": "Vídeo · 14 min",
     "vocab": [("hier", "ayer"), ("j'ai mangé", "comí / he comido"), ("j'ai fait", "hice / he hecho"),
               ("je suis allé", "fui / he ido"), ("j'ai vu", "vi / he visto"), ("j'ai bu", "bebí"),
               ("j'ai pris", "tomé / cogí"), ("je suis venu", "vine"), ("nous avons parlé", "hablamos"),
               ("le participe passé", "el participio"), ("déjà", "ya"), ("ne… pas encore", "todavía no"),
               ("la semaine dernière", "la semana pasada"), ("finir", "terminar")]},
    {"level": "A2", "title": "L'imparfait", "type": "video", "meta": "Vídeo · 11 min",
     "vocab": [("quand j'étais petit", "cuando era pequeño"), ("c'était", "era / estaba"),
               ("il faisait beau", "hacía buen tiempo"), ("il pleuvait", "llovía"), ("avant", "antes"),
               ("souvent", "a menudo"), ("il y avait", "había"), ("je jouais", "jugaba"),
               ("nous habitions", "vivíamos"), ("je voulais", "quería"), ("pendant que", "mientras"),
               ("d'habitude", "normalmente"), ("chaque jour", "cada día"), ("autrefois", "antiguamente")]},
    {"level": "A2", "title": "Le futur proche", "type": "ejercicio", "meta": "Ejercicio · 12 preguntas",
     "vocab": [("je vais partir", "voy a salir"), ("aller + infinitif", "ir a + infinitivo"),
               ("nous allons voir", "vamos a ver"), ("elle va venir", "ella va a venir"),
               ("qu'est-ce que tu vas faire ?", "¿qué vas a hacer?"), ("demain", "mañana"),
               ("bientôt", "pronto"), ("ce soir", "esta noche"), ("la semaine prochaine", "la semana que viene"),
               ("le mois prochain", "el mes que viene"), ("dans deux jours", "dentro de dos días"),
               ("plus tard", "más tarde"), ("tout à l'heure", "dentro de un rato")]},
    {"level": "A2", "title": "La routine (verbes pronominaux)", "type": "video", "meta": "Vídeo · RFI Français facile",
     "vocab": [("se lever", "levantarse"), ("se laver", "lavarse"), ("s'habiller", "vestirse"),
               ("se coucher", "acostarse"), ("se réveiller", "despertarse"),
               ("se brosser les dents", "cepillarse los dientes"), ("prendre le petit-déjeuner", "desayunar"),
               ("se reposer", "descansar"), ("le matin", "por la mañana"), ("le soir", "por la noche"),
               ("d'abord", "primero"), ("ensuite", "después"), ("tôt", "temprano"), ("tard", "tarde")]},
    {"level": "A2", "title": "Le corps et la santé", "type": "ejercicio", "meta": "Ejercicio · Liveworksheet",
     "vocab": [("la tête", "la cabeza"), ("le bras", "el brazo"), ("la jambe", "la pierna"),
               ("le ventre", "la barriga"), ("le dos", "la espalda"), ("le pied", "el pie"),
               ("la main", "la mano"), ("j'ai mal", "me duele"), ("être malade", "estar enfermo"),
               ("la fièvre", "la fiebre"), ("le rhume", "el resfriado"), ("le médecin", "el médico"),
               ("la pharmacie", "la farmacia"), ("un médicament", "un medicamento"), ("se sentir bien", "sentirse bien")]},
    {"level": "A2", "title": "Les courses (quantités, partitifs)", "type": "video", "meta": "Vídeo · 10 min",
     "vocab": [("du pain", "pan"), ("de l'eau", "agua"), ("de la viande", "carne"),
               ("les fruits", "las frutas"), ("les légumes", "las verduras"), ("un kilo de", "un kilo de"),
               ("une bouteille de", "una botella de"), ("une tranche de", "una loncha de"),
               ("beaucoup de", "mucho"), ("un peu de", "un poco de"), ("le marché", "el mercado"),
               ("combien ça coûte ?", "¿cuánto cuesta?"), ("payer", "pagar"), ("cher", "caro")]},
    {"level": "A2", "title": "Les vêtements", "type": "pdf", "meta": "PDF · 4 págs",
     "vocab": [("un pantalon", "un pantalón"), ("une chemise", "una camisa"), ("une robe", "un vestido"),
               ("des chaussures", "unos zapatos"), ("un manteau", "un abrigo"), ("un pull", "un jersey"),
               ("une veste", "una chaqueta"), ("un chapeau", "un sombrero"), ("porter", "llevar puesto"),
               ("mettre", "ponerse"), ("essayer", "probarse"), ("la taille", "la talla"),
               ("la couleur", "el color"), ("à la mode", "de moda")]},
    {"level": "A2", "title": "Les comparatifs", "type": "ejercicio", "meta": "Ejercicio · Le Point du FLE",
     "vocab": [("plus… que", "más… que"), ("moins… que", "menos… que"), ("aussi… que", "tan… como"),
               ("plus grand que", "más grande que"), ("moins cher que", "menos caro que"),
               ("meilleur", "mejor (adj.)"), ("mieux", "mejor (adv.)"), ("pire", "peor"),
               ("le meilleur", "el mejor"), ("le pire", "el peor"), ("le plus", "el más"),
               ("le moins", "el menos"), ("comme", "como"), ("de plus en plus", "cada vez más")]},
    {"level": "A2", "title": "Le logement", "type": "video", "meta": "Vídeo · 12 min",
     "vocab": [("un appartement", "un piso"), ("une maison", "una casa"), ("la cuisine", "la cocina"),
               ("la chambre", "la habitación"), ("la salle de bains", "el baño"), ("le salon", "el salón"),
               ("le jardin", "el jardín"), ("le balcon", "el balcón"), ("l'étage", "la planta"),
               ("l'ascenseur", "el ascensor"), ("louer", "alquilar"), ("le loyer", "el alquiler"),
               ("déménager", "mudarse"), ("meublé", "amueblado"), ("un voisin", "un vecino")]},
    {"level": "A2", "title": "Les projets et le futur", "type": "ejercicio", "meta": "Ejercicio · 10 preguntas",
     "vocab": [("je ferai", "haré"), ("j'irai", "iré"), ("nous partirons", "saldremos"),
               ("ils viendront", "vendrán"), ("l'année prochaine", "el año que viene"),
               ("quand je serai grand", "cuando sea mayor"), ("un projet", "un proyecto"),
               ("espérer", "esperar"), ("avoir l'intention de", "tener la intención de"),
               ("avoir envie de", "tener ganas de"), ("réussir", "conseguir / aprobar"),
               ("un rêve", "un sueño"), ("peut-être", "quizás"), ("dès que possible", "cuanto antes")]},
    {"level": "A2", "title": "Raconter une anecdote", "type": "video", "meta": "Vídeo · TV5Monde A2",
     "vocab": [("un jour", "un día"), ("au début", "al principio"), ("tout à coup", "de repente"),
               ("alors", "entonces"), ("puis", "luego"), ("après", "después"), ("enfin", "por fin"),
               ("finalement", "al final"), ("heureusement", "por suerte"), ("malheureusement", "por desgracia"),
               ("c'était drôle", "fue gracioso"), ("il m'est arrivé", "me pasó"), ("incroyable", "increíble"),
               ("raconter", "contar")]},
    {"level": "A2", "title": "Préparation DELF A2", "type": "pdf", "meta": "PDF · simulacro oficial",
     "vocab": [("la compréhension orale", "comprensión oral"), ("la production écrite", "expresión escrita"),
               ("l'oral", "el oral"), ("l'écrit", "el escrito"), ("une consigne", "una instrucción"),
               ("répondre", "responder"), ("décrire", "describir"), ("exprimer une opinion", "expresar una opinión"),
               ("le vocabulaire", "el vocabulario"), ("la grammaire", "la gramática"), ("un examen", "un examen"),
               ("la note", "la nota"), ("réussir l'examen", "aprobar el examen"), ("s'entraîner", "practicar"),
               ("bonne chance", "buena suerte")]},
]
